// Languages
export const SET_LANG = "SET_LANG";

// Navigation
export const SET_MENU_STATE = "SET_MENU_STATE";

// Search
export const SET_CITIES = "SET_CITIES";
export const SET_REGION = "SET_REGION";
export const SET_HEAT_MAP = "SET_HEAT_MAP";
export const SET_EDITOR_SUGGESTION_LIST = "SET_EDITOR_SUGGESTION_LIST";
export const SET_DETAILS_COORDS = "SET_DETAILS_COORDS";
export const SET_CURRENT_MOSQUES_LIST = "SET_CURRENT_MOSQUES_LIST";
export const SET_MOSQUE_DETAILS = "SET_MOSQUE_DETAILS";
export const SET_COMPONENT_NAME = "SET_COMPONENT_NAME";

// Contact
export const SET_CONTACT_FORM_DATA = "SET_CONTACT_FORM_DATA";
